myblog/urls.py
from django.conf.urls import patterns, url
from myblog import views
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    #items
    url(r'^$',views.home,name='home'),
    url(r'^message/$',views.message,name='message'),
    url(r'^write/$',views.write,name='write'),
    url(r'^article/(?P<id>\d+)/$',views.article,name='article'),
    url(r'^article/(?P<page>\d+)/edit/$',views.edit_article,name='edit_article'),
    
    
    #catergory

]

yunjz_jz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^$',views.index0,name='index0'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^jizhang/', include('jizhang.urls',namespace='jizhang')),
    url(r'^myblog/', include('myblog.urls',namespace='myblog')),
    url(r'^comments/', include('django_comments.urls',namespace='comments')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jizhang/models.py
#coding:utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


class Category(models.Model):

    INCOME_CHOICE=(
        (True,u'收入'),
        (False,u'支出'),
        )
    name=models.CharField(max_length=20,verbose_name=u'类别名称')
    user=models.ForeignKey(User,verbose_name=u'用户名')
    p_category=models.ForeignKey('self',verbose_name=u'父类名',null=True,blank=True,related_name='childs')
    isincome=models.BooleanField(choices=INCOME_CHOICE,verbose_name=u'收入OR支出')


    def __unicode__(self):
        return self.leve()+self.name

    def leve(self):
        if self.p_category!=None:
            return '--'+self.p_category.leve()
        else:
            return ''

    def get_absolute_url(self):
        return '%s' %(reverse('jizhang:edit_category',args=(self.id,)))

    def get_items_url(self):
        return '%s' %(reverse('jizhang:show_category',args=(self.id,)))

    def save(self, *args, **kwargs):
    #form保证了子类不能修改isIncome，只能修改顶级父类的isIncome
    #遍历一遍childs，统一设置isIncome
        for child in self.childs.all():
            if child.isIncome != self.isIncome:
                child.isIncome = self.isIncome
                child.save()              
        super(self.__class__, self).save(*args, **kwargs)


class Item(models.Model):

    price=models.DecimalField(max_digits=20, decimal_places=2, verbose_name=u'金额')
    pub_date=models.DateField(verbose_name=u'日期')
    category=models.ForeignKey(Category,verbose_name=u'所属分类',related_name='items')
    comment=models.CharField(max_length=200,blank=True,verbose_name=u'备注',)

    class Meta:
        ordering=['-pub_date']

    def unicode(self):
        return str(self.price)

    def get_item_url(self):
        return '%s'%(reverse('jizhang:edit_item',args=(self.id,)))

    def git_price(self):
        if self.isincome:
            return self.price  
        else:
            return -1*self.price

    def save(self, *args, **kwargs):
        if self.price<0:
            self.price = -1*self.price
        super(Item, self).save(*args, **kwargs)




def gen_test_data():
    u1=User.objects.create_user(username='xiaozhou',password='zhoubo3923')
    #u1=User.objects.filter(username='xiaozhou')[0]
    u2=User.objects.create_user(username='xiaoweng',password='zhoubo3923')
    #u2=User.objects.filter(username='xiaoweng')[0]
    u_list=[u1,u2]

    for u in u_list:
        c1=Category(name='salary',isincome=True,p_category=None,user=u)
        c1.save()
        c2=Category(name='salary_lp',isincome=True,p_category=c1,user=u)
        c2.save()

        base_salary=2000 if u.username=='xiaozhou' else 1500

        for i in range(10):

            i=Item(price=base_salary*(1.0+i/10.0),category=c2,pub_date='2015-%d-1'%(i+1),comment='gong zi')
            i.save()

myblog/models.py
#coding:utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=20,verbose_name=u'分类名')
    p_category=models.ForeignKey('self',blank=True,null=True,verbose_name='上级分类',related_name='childs')

    def __unicode__(self):
        return self.get_level()+self.name

    def get_level(self):
        if self.p_category!=None:
            return '--'+self.p_category.get_level()
        else:
            return ''


class Article(models.Model):
    title = models.CharField(max_length=50,verbose_name=u'标题')
    content=models.TextField()
    write_date=models.DateTimeField(auto_now_add=True,verbose_name=u'写作时间')
    change_date=models.DateTimeField(auto_now=True,verbose_name=u'最后修改时间')
    category=models.ForeignKey(Category,verbose_name=u'所属分类')

    class Meta:
        ordering=['-write_date']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return '%s'%(reverse('myblog:article',args=(self.id,)))




class Comment_to_me(models.Model):
    user=models.ForeignKey(User,verbose_name=u'用户')
    comment_date=models.DateTimeField(auto_now_add=True,verbose_name=u'评论时间')
    content=models.CharField(max_length=200,verbose_name=u"评论内容")

    class Meta:
        ordering=['-comment_date']

    def __unicode__(self):
        return self.content

class Comment_to_article(Comment_to_me):
    article=models.ForeignKey(Article,verbose_name=u'被评论文章')


class User_profile(models.Model):
    phone_number=models.IntegerField(verbose_name=u'电话')
    level=models.IntegerField(verbose_name=u'等级')
    image=models.ImageField(max_length=150,verbose_name=u'头像')
    user=models.ForeignKey(User,verbose_name=u'用户')


    def __unicode__(self):
        return self.user



def increase_article():
    c=Category(name='python')
    c.save()
    c1=Category(name='Django',p_catagory=c)
    c1.save()
    content="""这是测试的内容，Django是构建web应用很快的一个工具。
    Django，你可以从概念到启动Web应用程序在几个小时内。Django照顾很多Web开发的麻烦，因此您可以专注于编写您的应用程序，而不需要重新发明轮子。它是免费的和开放源代码。
    """
    article=Article(title=u'用Django构建自己的一个应用',content=content,category=c1)
    article.save()

myblog/forms.py
from django import forms
from myblog.models import Article
from ckeditor.widgets import CKEditorWidget
from myblog.func_lib import get_result 


class Article_form(forms.ModelForm):

    class Meta:
        model=Article
        fields=('title','content','category')

    def __init__(self,*args,**kwargs):
        super(Article_form, self).__init__(*args, **kwargs)
        self.fields['content'].widget=CKEditorWidget(attrs={'class':'form-control'})
        self.fields['title'].widget=forms.TextInput(attrs={'class':'form-control'})
        choices=[('','----')]+[(i.id,i) for i in get_result()]
        self.fields['category'].widget=forms.Select(choices=choices,attrs={'class':'form-control'})

myblog/views.py
from django.shortcuts import render
from myblog.models import Article,Category,Comment_to_me
from django.http import HttpResponseRedirect,HttpResponse
from myblog.forms import Article_form
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger


def home(request):
    articles=Article.objects.all()
    articles=get_paginator(articles,8,request)
    return render(request,'myblog/home.html',{'articles':articles})

def message(request):
    if request.method=='POST':
        content=request.POST.get('comment_to_me')
        comment_to_me=Comment_to_me(user=request.user,content=content)
        comment_to_me.save()
    comment_list=Comment_to_me.objects.all()
    comment_list=get_paginator(comment_list,20,request)
    return render(request,'myblog/message.html',{'comment_list':comment_list})
        
    return render(request,'myblog/message.html')
def write(request):
    form=Article_form()
    if request.method=='POST':
        title=request.POST.get('title')
        content=request.POST.get('content')
        category=Category.objects.get(id=1)
        article=Article(title=title,content=content,category=category)
        article.save()
        return HttpResponseRedirect('/myblog')
    return render(request,'myblog/write.html',{'form':form})
def article(request,id):
    if request.method=='POST':
        pass
    article=Article.objects.get(id=id)
    if article:
        return render(request,'myblog/article.html',{'article':article})
def edit_article(request,page):
    pass



def get_paginator(obj_list,num,request):
    paginator=Paginator(obj_list,num)
    page=request.GET.get('page')
    try:
        res_list=paginator.page(page)
    except EmptyPage:
        res_list=paginator.page(1)
    except  PageNotAnInteger:
        res_list=paginator.page(paginator.num_pages)
    return res_list

templates/myblog/article.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">{{article.title}}</h1>
  </div>
  <div class="panel-body">
    {{article.content |safe }}
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">评论</h3>
  </div>
  <div class="panel-body">
    <form action="" method>
        {% csrf_token %}
        <textarea class="form-control" rows="3"placeholder="请在这里输入评论，最多200字" ></textarea>
        <input type="submit" value="提交" class="btn btn-default">
    </form>
  </div>
  <div class="panel-body">
    评论列表
  </div>
</div>
{% endblock %}

templates/myblog/home.html
{%extends 'base.html' %}
{% load staticfiles %}
{% block content %}
  {%for article in articles %}
    <div class="panel panel-{% cycle 'default' 'info'%}">
      <div class="panel-heading">
        <h3 class="panel-title">{{article.title}}</h3>
      </div>
      <div class="panel-body">
        {{ article.content|slice:"100"|safe }}......
      </div>
      <div class="panel-footer">
        创建于：{{article.write_date}},最后修改于：{{article.change_date}}
        <a href="{{article.get_absolute_url}}" >[阅读全文]</a>
      </div>
    </div>
  {% endfor %}
  <nav>
        <ul class="pager">
          <p class="text-center">共{{articles.paginator.num_pages}}页</p>
                    <li>
                    {% if articles.has_previous %}
                    <a href="?page={{articles.previous_page_number}}" aria-label="上一页">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                    {% endif %}
                    </li>
                    <li><a href="">{{articles.number}}</a></li>
                    <li>
                    {% if articles.has_next %}
                    <a href="?page={{articles.next_page_number}}" aria-label="下一页">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                    {% endif %}
                    </li>
        </ul>
    </nav>
{% endblock %}
{%block main-right%}
<div class="row">
    <ul class="list-group">
        <li class="list-group-item">
          <span class="badge">14</span>
          Cras justo odio
        </li>
    </ul>
</div>
{%endblock%}

templates/myblog/index.html
{%extends 'base.html' %}
{% load staticfiles %}

templates/myblog/main-right.html
{%extends 'base.html'%}
{% load static %}


{%block main-right%}
<div class="row">
    <ul class="list-group">
        <li class="list-group-item">
          <span class="badge">14</span>
          Cras justo odio
        </li>
    </ul>
</div>
<div id="datepicker"></div>
{%endblock%}
{% block extra-script %}
$('#datepicker').datatimepicker()
{%endblock%}

templates/myblog/message.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    评论列表
  </div>
<div class="panel-body">
    <form action="" method="post" onsubmit="return valid_form()">
        {% csrf_token %}
        <textarea class="form-control" rows="3"placeholder="请在这里输入评论，最多200字" id="id_comment" name="comment_to_me"></textarea>
        <input type="submit" value="提交" class="btn btn-default" id="submit_comment_to_me" >
    </form>
  </div>
  <div class="panel-body">
    {% for i in comment_list %}
    <div class="panel panel-{% cycle 'info' 'default' %}">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>{{i.user}}</strong>于{{i.comment_date}}评价:</h3>
      </div>
      <div class="panel-body">
      {{i.content|safe}}
      </div>
  </div>
    {% endfor %}
</div>
  <nav>
        <ul class="pager">
          <p class="text-center">共{{comment_list.paginator.num_pages}}页</p>
                    <li>
                    {% if comment_list.has_previous %}
                    <a href="?page={{comment_list.previous_page_number}}" aria-label="上一页">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                    {% endif %}
                    </li>
                    <li><a href="">{{comment_list.number}}</a></li>
                    <li>
                    {% if comment_list.has_next %}
                    <a href="?page={{comment_list.next_page_number}}" aria-label="下一页">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                    {% endif %}
                    </li>
        </ul>
    </nav>
</div>
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" id="mymodal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <h3>你还么有权限，请先<a href="/accounts/login" >登录</a></h3>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_script %}
<script>
  $('#id_comment').click(function(){
    if ('{{request.user.is_authenticated}}'!='True'){
      $('#mymodal').modal()
    }
  });
  function valid_form(){
    var value=$('#id_comment').val();
    if (value==null||value==""){
      alert('提交内容不能为空')
      return false
  };    
  }
</script>
{% endblock%}

templates/myblog/write.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="pael panel-dafault">
    <form action="" method="post">
        {%csrf_token%}
            <div class="form-group">
                <label for="id_title">标题</label>
                {{form.title}}
            </div>
            <div class="form-group">
                <label for="id_content">内容</label>
                {{form.media}}
                {{form.content}}
            </div>
            <div class="check-box">
                <label for="id_p_category">分类</label>
                {{form.category}}
            </div>
        <input type="submit" value="提交" class="btn btn-success">
        <a href="{% url 'myblog:home'%}" class="btn btn-default">返回</a>
    </form>
</div>
{% endblock%}