accounts/urls.py
from django.conf.urls import url
from accounts import views 





urlpatterns = [
    url(r'^login/',views.accounts_login,name='login'),
    url(r'^logout/',views.accounts_logout,name='logout'),
    url(r'^register/',views.register,name='register'),
    url(r'^index/',views.index,name='index'),
]

myblog/urls.py
from django.conf.urls import patterns, url
from myblog import views
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    #items
    url(r'^$',views.home,name='home'),
    url(r'^message/$',views.message,name='message'),
    url(r'^write/$',views.write,name='write'),
    url(r'^article/(?P<id>\d+)/$',views.article,name='article'),
    url(r'^article/(?P<page>\d+)/edit/$',views.edit_article,name='edit_article'),
    
    
    #catergory

]

yunjz_jz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^$',views.index0,name='index0'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^jizhang/', include('jizhang.urls',namespace='jizhang')),
    url(r'^myblog/', include('myblog.urls',namespace='myblog')),
    url(r'^comments/', include('django_comments.urls',namespace='comments')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

accounts/forms.py
#coding:utf-8
from django import forms
from django.contrib.auth.models import User
import re
from django.contrib.auth import authenticate

alnum_re=re.compile(r'^[\w^_]{6,12}$')

class Register_forms(forms.Form):

        username=forms.CharField(
                label='Username',
                max_length=100,
                required=True,
                widget=forms.TextInput(attrs={'class':'form-control' ,'placeholder':'Username'})            
        )
        password=forms.CharField(
                label='Password',
                required=True,
                widget=forms.PasswordInput(attrs={'class':'form-control' ,'placeholder':'Password'}),
                
        )
        password_confirm=forms.CharField(
                label='Password(Again)',
                required=True,
                widget=forms.PasswordInput(attrs={'class':'form-control' ,'placeholder':'Repassword'}),
                
        )
        email=forms.EmailField(
                widget=forms.EmailInput(attrs={'class':'form-control' ,'placeholder':'Email'}),
                required=True,
                
        )


        def clean_username(self):

                if not alnum_re.search(self.cleaned_data['username']):
                        raise forms.ValidationError(u'用户名由数字和子母组成且6到12位')
                flags=User.objects.filter(username__iexact=self.cleaned_data['username']).exists()
                if not flags :
                        return self.cleaned_data['username']
                else:
                      raise forms.ValidationError(u'用户名已被注册，请重新注册')


        def clean_email(self):

                user=User.objects.filter(email__iexact=self.cleaned_data['email'])
                if not user:
                        return self.cleaned_data['email']
                else:
                      raise forms.ValidationError(u'邮箱已经被注册了')

        def clean(self):
                cleaned_data=super(Register_forms,self).clean()
                if cleaned_data.get('password') != cleaned_data.get('password_confirm'):
                    raise forms.ValidationError(u'两次密码必须一致')
                return cleaned_data            
                


class Login_forms(forms.Form):

        username=forms.CharField(
                    label='Username',
                    widget=forms.TextInput(attrs={'class':'form-control' ,'placeholder':'Username'})
               )
        password=forms.CharField(
                    label='Password',
                    widget=forms.PasswordInput(attrs={'class':'form-control' ,'placeholder':'Password'})
               )



        def clean(self):

            cleaned_data=super(Login_forms,self).clean()
            user=User.objects.filter(username=cleaned_data.get('username'))
            username=cleaned_data.get('username')
            password=cleaned_data.get('password')
            if (not password) or (not username) :
                raise forms.ValidationError(u'密码或用户名不能为空')
            if not len(user)>0:
                raise   forms.ValidationError(u'用户名不存在')
            else:
                user = authenticate(username=cleaned_data.get('username'),password=password)
                if user:
                    return cleaned_data
                else:
                    raise forms.ValidationError(u'用户名和密码不匹配')

            
            

accounts/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from accounts.forms import Register_forms
from accounts.forms import Login_forms
from jizhang.func_lib import auto_gen_categories

# Create your views here.
def index0(request):
        return HttpResponseRedirect('/myblog/')
@login_required
def index(request):
        username=request.user.username
        return  render(request,'accounts/index.html',{'username':username})
def accounts_logout(request):
        logout(request)
        return  HttpResponseRedirect('/myblog/')
def  accounts_login(request):
                if request.method=='POST':
                        form=Login_forms(request.POST)
                        if form.is_valid():
                                username=form.cleaned_data['username']
                                password=form.cleaned_data['password']
                                user = authenticate(username=username,password=password)
                                if user :
                                        if user.is_active:
                                                login(request,user)
                                                return HttpResponseRedirect('/myblog/')
                                        else:
                                                return HttpResponse('your password in valid,but the account has been disable')
                                else:
                                        return HttpResponse('your username and password is invalid')
                        else:   
                                return render(request,'accounts/login.html',{'form':form})
                else:
                        form=Login_forms()
                        return  render(request,'accounts/login.html',{'form':form})
def register(request):
        if request.method=='POST':
                form=Register_forms(request.POST)
                if form.is_valid():
                        username=form.cleaned_data['username']
                        password=form.cleaned_data['password']
                        email=form.cleaned_data['email']
                        user=User.objects.create_user(username=username,password=password,email=email)
                        user.save()
                        user1 = authenticate(username=username,password=password)
                        login(request,user1)
                        auto_gen_categories(user)
                        return HttpResponseRedirect('/myblog/')
                else:
                        return  render(request,'accounts/register.html',{'form':form})
        form=Register_forms()
        return  render(request,'accounts/register.html',{'form':form})

templates/accounts/index.html
{%extends 'base.html'%}
{%load staticfiles%}
{%block title%}
<title>welcome</title>
{%endblock%}
{%block content%}
{%include 'welcome.html'%}
<img src="{%static 'images/rango.png'%}">
{%endblock%}

templates/accounts/login.html
{%extends 'base.html'%}
{%block title%}
<title>login</title>
{%endblock%}
{%block content%}
        <h1 class="text-center">爱生活，爱记账</h1>
         {%if form.non_field_errors %}
            {%for errors_string in form.non_field_errors%}
            <p>{{errors_string}}</p>
            {%endfor%}
         {%endif%}
        <form action="" method="post" >
                {% csrf_token%}
                        <div class="form-group ">
                            <label for="id_username" >用户名</label>
                               {{form.username.errors}}
                               {{form.username}}
                        </div>
                        <div class="form-group ">
                            <label for="id_password" >密码</label>
                               {{form.password.errors}}
                               {{form.password}}
                        </div>
                        <div class="form-group ">
                            <button type="submit" class="btn btn-default" >登录</button>
                            <button type="button" class="btn btn-default" onclick='javascript:window.location.href="{% url 'accounts:register' %}"'>注册</button>
                        </div>
        </form>
        <h3> 在这里你可以</h3>
        <ul>
            <li>随时随地通过网络记账</li>
            <li>统计分析自己每月收支</li>
            <li>导出表格进行备份</li>
            <li>导入以前记录的表格</li>
        </ul>

{%endblock%}

templates/accounts/logout.html
{%extends 'base.html'%}
{%block title%}
<title>logout</title>
{%endblock%}
{%block content%}
<h1>谢谢惠顾<h1>
<h1><a href="/accounts/login">登录</a><h1>
{%endblock%}

templates/accounts/register.html
{%extends 'base.html'%}
{%block title%}
<title>register</title>
{%endblock%}
{%block content%}
                <h2 class="text-center">注册成为我们的一员吧</h2>
                <p>
                {%if form.non_field_errors %}
                {{form.non_field_errors}}
                {%endif%}
                </p>
        <form action="" method="post" >
                {%csrf_token%}
                <div class="form-group ">
                            <label for="id_username" >用户名</label>
                            {{form.username.errors}}               
                            {{form.username}}                              
                </div>
                <div class="form-group ">
                            <label for="id_password" >密码</label>
                            {{form.password.errors}}               
                            {{form.password}}                              
                </div>
                <div class="form-group ">
                            <label for="id_password_confirm" >密码(Again)</label>
                            {{form.password_confirm.errors}}               
                            {{form.password_confirm}}                              
                </div>
                <div class="form-group ">
                            <label for="id_email" >Email</label>
                            {{form.email.errors}}               
                            {{form.email}}                              
                </div>
                <div class="form-group ">
                    <input type="submit" name="submit" value="注册" class="btn btn-default">
                    <button type="button"  class="btn btn-default" onclick='javascript:window.location.href="{% url 'accounts:login' %}"'>登录</button>
                </div>
        </form>
{%endblock%}
{%include 'footer.html'%}