accounts/urls.py
from django.conf.urls import url
from accounts import views 





urlpatterns = [
    url(r'^login/',views.accounts_login,name='login'),
    url(r'^logout/',views.accounts_logout,name='logout'),
    url(r'^register/',views.register,name='register'),
    url(r'^index/',views.index,name='index'),
]

jizhang/urls.py
from django.conf.urls import patterns, include, url
from jizhang import views
from django.contrib import admin
admin.autodiscover()

urlpatterns =[
    #item
    url(r'^$',views.items,name='items'),
    url(r'^(?P<pk>\d+)/edit/$',views.edit_item,name='edit_item'),
    url(r'^new/$',views.new_item,name='new_item'),
    #category
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/(?P<pk>\d+)/$',views.show_category,name='show_category'),
    url(r'^category/(?P<pk>\d+)/edit/$',views.edit_category, name='edit_category'),
    url(r'^category/new/$',views.new_category, name='new_category'),
    #ajax
    url(r'^ajax/autocomplete_comments/',views.autocomplete_comments),
]

myblog/urls.py
from django.conf.urls import patterns, url
from myblog import views
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    #items
    url(r'^$',views.home,name='home'),
    url(r'^message/$',views.message,name='message'),
    url(r'^write/$',views.write,name='write'),
    url(r'^article/(?P<id>\d+)/$',views.article,name='article'),
    url(r'^article/(?P<page>\d+)/edit/$',views.edit_article,name='edit_article'),
    
    
    #catergory

]

yunjz_jz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^$',views.index0,name='index0'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^jizhang/', include('jizhang.urls',namespace='jizhang')),
    url(r'^myblog/', include('myblog.urls',namespace='myblog')),
    url(r'^comments/', include('django_comments.urls',namespace='comments')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{%static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{%static 'css/blog.css'%}" />
    <script src="{%static 'bootstrap/js/jquery-3.0.0.min.js'%}"></script>
    <script src="{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
    {%block title%}        
    <title>博客首页</title>
    {%endblock%}
    {%block extrahead%}
    {%endblock%}
  </head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
  <ul class="nav navbar-nav">
    <li class="active"><a href="{% url "myblog:home"%}">首页</a></li>
    <li><a href="{%url "jizhang:items"%}">记账</a></li>
    <li><a href="{%url "myblog:message"%}">留言区</a></li>
    {%if request.user.is_staff %}<li><a href="{%url 'myblog:write'%}">写作</a></li>{% endif %}
  </ul>
  <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">GO!</button>
  </form>
  <p class="navbar-text navbar-right" >
    {% if request.user.is_authenticated %}
    {{request.user.username}}<a href="{%url 'accounts:logout'%}" class="navbar-link"><strong> ,注销</strong></a>
    {% else %}
    <a href="{% url 'accounts:login'%}" class="navbar-link"><strong>登录</strong></a>
    {% endif %}
  </p>
</div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-8">
      {% block content%}
      {% endblock %}
      {% include 'footer.html'%}
    </div>
    <div class="col-xs-6 col-md-4">
      {% block main-right%}
      {% endblock %}
    </div>
  </div>
</div>
<script src="{%static 'bootstrap/js/jquery-3.0.0.min.js'%}"></script>
<script src="{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{%static 'bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js'%}"></script>
<script src="{%static 'bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.fr.js'%}"></script>
{%block extra_script%}
{%endblock%}
</body>
</html>

templates/footer.html
<div class="text-center">
        <a href="https://www.djangoproject.com"><h5>Powered By Django</h5></a>  
</div>

templates/welcome.html
<h5 class="text-right">欢迎,<strong>{{request.user}}</strong>,
        <a href="/accounts/logout">注销</a>
</h5>