jizhang/urls.py
from django.conf.urls import patterns, include, url
from jizhang import views
from django.contrib import admin
admin.autodiscover()

urlpatterns =[
    #item
    url(r'^$',views.items,name='items'),
    url(r'^(?P<pk>\d+)/edit/$',views.edit_item,name='edit_item'),
    url(r'^new/$',views.new_item,name='new_item'),
    #category
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/(?P<pk>\d+)/$',views.show_category,name='show_category'),
    url(r'^category/(?P<pk>\d+)/edit/$',views.edit_category, name='edit_category'),
    url(r'^category/new/$',views.new_category, name='new_category'),
    #ajax
    url(r'^ajax/autocomplete_comments/',views.autocomplete_comments),
]

myblog/urls.py
from django.conf.urls import patterns, url
from myblog import views
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    #items
    url(r'^$',views.home,name='home'),
    url(r'^message/$',views.message,name='message'),
    url(r'^write/$',views.write,name='write'),
    url(r'^article/(?P<id>\d+)/$',views.article,name='article'),
    url(r'^article/(?P<page>\d+)/edit/$',views.edit_article,name='edit_article'),
    
    
    #catergory

]

yunjz_jz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^$',views.index0,name='index0'),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^jizhang/', include('jizhang.urls',namespace='jizhang')),
    url(r'^myblog/', include('myblog.urls',namespace='myblog')),
    url(r'^comments/', include('django_comments.urls',namespace='comments')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jizhang/models.py
#coding:utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


class Category(models.Model):

    INCOME_CHOICE=(
        (True,u'收入'),
        (False,u'支出'),
        )
    name=models.CharField(max_length=20,verbose_name=u'类别名称')
    user=models.ForeignKey(User,verbose_name=u'用户名')
    p_category=models.ForeignKey('self',verbose_name=u'父类名',null=True,blank=True,related_name='childs')
    isincome=models.BooleanField(choices=INCOME_CHOICE,verbose_name=u'收入OR支出')


    def __unicode__(self):
        return self.leve()+self.name

    def leve(self):
        if self.p_category!=None:
            return '--'+self.p_category.leve()
        else:
            return ''

    def get_absolute_url(self):
        return '%s' %(reverse('jizhang:edit_category',args=(self.id,)))

    def get_items_url(self):
        return '%s' %(reverse('jizhang:show_category',args=(self.id,)))

    def save(self, *args, **kwargs):
    #form保证了子类不能修改isIncome，只能修改顶级父类的isIncome
    #遍历一遍childs，统一设置isIncome
        for child in self.childs.all():
            if child.isIncome != self.isIncome:
                child.isIncome = self.isIncome
                child.save()              
        super(self.__class__, self).save(*args, **kwargs)


class Item(models.Model):

    price=models.DecimalField(max_digits=20, decimal_places=2, verbose_name=u'金额')
    pub_date=models.DateField(verbose_name=u'日期')
    category=models.ForeignKey(Category,verbose_name=u'所属分类',related_name='items')
    comment=models.CharField(max_length=200,blank=True,verbose_name=u'备注',)

    class Meta:
        ordering=['-pub_date']

    def unicode(self):
        return str(self.price)

    def get_item_url(self):
        return '%s'%(reverse('jizhang:edit_item',args=(self.id,)))

    def git_price(self):
        if self.isincome:
            return self.price  
        else:
            return -1*self.price

    def save(self, *args, **kwargs):
        if self.price<0:
            self.price = -1*self.price
        super(Item, self).save(*args, **kwargs)




def gen_test_data():
    u1=User.objects.create_user(username='xiaozhou',password='zhoubo3923')
    #u1=User.objects.filter(username='xiaozhou')[0]
    u2=User.objects.create_user(username='xiaoweng',password='zhoubo3923')
    #u2=User.objects.filter(username='xiaoweng')[0]
    u_list=[u1,u2]

    for u in u_list:
        c1=Category(name='salary',isincome=True,p_category=None,user=u)
        c1.save()
        c2=Category(name='salary_lp',isincome=True,p_category=c1,user=u)
        c2.save()

        base_salary=2000 if u.username=='xiaozhou' else 1500

        for i in range(10):

            i=Item(price=base_salary*(1.0+i/10.0),category=c2,pub_date='2015-%d-1'%(i+1),comment='gong zi')
            i.save()

jizhang/forms.py
#coding:utf-8
from django import forms
from jizhang.models import Category,Item
from jizhang.func_lib import sorted_categories

class Category_form(forms.ModelForm):

    class Meta:
        model=Category
        fields=('name','p_category','isincome')

    def __init__(self, request, *args, **kwargs):
        super(Category_form, self).__init__(*args, **kwargs)
        self.user=request.user
        self.fields['name'].widget=forms.TextInput(attrs={'class':'form-control','placeholder':'分类名'})
        categories=sorted_categories(self.user.username)
        choices=[('',u'-----------')]+[(i.id,i) for i in categories]
        self.fields['p_category'].widget=forms.Select(attrs={'class':'form-control'},choices=choices)
        self.fields['isincome'].widget=forms.CheckboxInput(attrs={'value':'True'})

    def clean_isincome(self):
        if self.cleaned_data['p_category']:
            if not self.cleaned_data['p_category'].isincome==self.cleaned_data['isincome']:
                raise forms.ValidationError(u'是否和父类收入一致')
        return self.cleaned_data['isincome']

    def save(self,id=None):
        new_category=Category(name=self.cleaned_data['name'],
            user=self.user,
            p_category=self.cleaned_data['p_category'],
            isincome=self.cleaned_data['isincome'],
            id=id)
        new_category.save()




class Newcategory(Category_form):
    pass

class Item_form(forms.ModelForm):
    class Meta:
        model = Item
        fields =('price','pub_date','category','comment')

    def __init__(self,request,*args,**kwargs):
        super(Item_form,self).__init__(*args, **kwargs)
        self.user=request.user
        self.fields['price'].widget=forms.TextInput(attrs={'class':'form-control'})
        categories=sorted_categories(self.user.username)
        choices=[('',u'-----------')]+[(i.id,i) for i in categories]
        self.fields['category'].widget=forms.Select(attrs={'class':'form-control'},choices=choices)
        self.fields['pub_date'].widget=forms.TextInput(attrs={'class':'datepicker form-control'})
        self.fields['comment'].widget=forms.TextInput(attrs={'class':'form-control'})

    def save(self,id=None):
        new_item=Item(price=self.cleaned_data['price'],
            category=self.cleaned_data['category'],
            pub_date=self.cleaned_data['pub_date'],
            comment=self.cleaned_data['comment'],id=id)
        new_item.save()

class New_item_form(Item_form):
    pass

jizhang/views.py
#coding:utf-8
from django.shortcuts import render
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from jizhang.models import Category,Item
from jizhang.forms import Newcategory,New_item_form
from jizhang.func_lib import sorted_categories
# Create your views here.


@login_required
def items(request):
    user=request.user
    if request.method=='POST':
        item_id=request.POST.getlist('checkbox')
        item_id=map(lambda x:int(x),item_id)
        if len(item_id)>0:
            for i in item_id:
                item=Item.objects.get(id=i)
                item.delete()
    items=Item.objects.filter(category__user__username=user.username)
    paginator=Paginator(items,12)
    page=request.GET.get('page')
    try:
        items_listt=paginator.page(page)
    except EmptyPage:
        items_list=paginator.page(1)
    except PageNotAnInteger:
        items_list=paginator.page(paginator.num_pages)
    return render(request,'jizhang/items.html',{'items':items_list})


@login_required
def edit_item(request,pk):
    if request.method=='POST':
        form=New_item_form(request,data=request.POST)
        if form.is_valid():
            form.save(id=pk)
            return HttpResponseRedirect('/jizhang/')
        else:
            return render(request,'jizhang/new_item.html',{'form':form})
    instance=Item.objects.get(id=pk)
    form=New_item_form(request,instance=instance)
    return render(request,'jizhang/new_item.html',{'form':form})

@login_required
def new_item(request):
    if request.method=='POST':
        form=New_item_form(request, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/jizhang/')
        else:
            return render(request,'jizhang/new_item.html',{'form':form})
    form=New_item_form(request)
    return render(request,'jizhang/new_item.html',{'form':form})

@login_required
def categories(request):
    user=request.user
    if request.method=='POST':
        cate_id=request.POST.getlist('checkbox')
        cate_id=map(lambda x:int(x),cate_id)
        if len(cate_id)>0:
            for id in cate_id:
                category=Category.objects.get(id=id)
                category.delete()
    categories=sorted_categories(user.username)
    paginator=Paginator(categories,12)
    page=request.GET.get('page')
    try:
        categories_list=paginator.page(page)
    except  PageNotAnInteger:
        categories_list=paginator.page(1)
    except EmptyPage:
        categories_list=paginator.page(paginator.num_pages)

    return render(request,'jizhang/categories.html',{'categories':categories_list})

@login_required
def show_category(request,pk):
    pass

@login_required
def edit_category(request,pk):
    if request.method=='POST':
        form=Newcategory(request,data=request.POST)
        if form.is_valid():
            form.save(id=pk)
            return HttpResponseRedirect('/jizhang/categories/')
        else:
            return render(request,'jizhang/new_category.html',{'form':form})
    instance=Category.objects.get(id=pk)
    form=Newcategory(request,instance=instance)
    return render(request,'jizhang/new_category.html',{'form':form})

@login_required
def new_category(request):
    if request.method=='POST':
        form=Newcategory(request,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/jizhang/categories/')
        else:
            return render(request,'jizhang/new_category.html',{'form':form})
    form=Newcategory(request)
    return render(request,'jizhang/new_category.html',{'form':form})
@login_required
def autocomplete_comments(request):
    pass

templates/jizhang/categories.html
{%extends 'base.html'%}
{%load staticfiles%}
{%block title%}
<title>categories</title>
{%endblock%}
{%block content%}
{%block extrahead%}
{%endblock%}
<div class="btn-group btn-group-justified" role="group">
    <a href="{%url 'jizhang:new_category'%}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> 新建</a>
    <a href="" class="btn btn-primary"><span class="glyphicon glyphicon-download"></span> 导出</a>
    <a href="" class="btn btn-primary"><span class="glyphicon glyphicon-upload"></span> 导入</a>
    <a href="" class="btn btn-danger" data-toggle="modal" data-target="#myModal" id="submit"><span class="glyphicon glyphicon-trash"></span> 删除</a>
</div>
<form action="" method="post" name="category">
    {% csrf_token %}
<div class="table-response ">
    <table class="table table-hover">
            <tr class="info">
                <td><strong>类别名称</strong></td>
                <td><strong>所属用户</strong></td>
                <td><strong>上级分类</strong></td>
                <td><strong>是否是收入</strong></td>
                <td><strong><input type="checkbox" name="check_all" value="True" id="all" >全选</strong></td>
                    
            </tr>
        {%for i in categories%}
            <tr class="{% cycle '' 'active' %}">
                <td data-toggle="tooltip" data-placement="right" title="编辑该分类"><a href="{{i.get_absolute_url}}">{{i.leve}}{{i.name}}</a></td>
                <td>{{i.user}}</td>
                <td>{{i.p_category}}</td>
                <td>{{i.get_isincome_display}} </td>
                <td><input type="checkbox" value="{{i.id}}" class="del_id" name="checkbox"></td>
            </tr>
        {% endfor %}
    </table>
    <nav>
    <ul class="pager">
                <li>
                {% if categories.has_previous %}
                <a href="?page={{categories.previous_page_number}}" aria-label="上一页">
                    <span aria-hidden="true">&laquo;</span>
                </a>
                {% endif %}
                </li>
                <li><a href="">{{categories.number}}</a></li>
                <li>
                {% if categories.has_next %}
                <a href="?page={{categories.next_page_number}}" aria-label="下一页">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                {% endif %}
                </li>
    </ul>
    </nav>   
</div>
{% include 'jizhang/delete-modal.html'%}    
</form>
{%include 'jizhang/foot_botton.html'%}

{%endblock%}
{%block extra_script%}
<script>
    $(function () {
        $("#all").click(function () {
            var checked_status = this.checked;
            $(".del_id").each(function () {
                this.checked = checked_status;
            });
        });
    });
</script>
{% endblock%}

templates/jizhang/delete-modal.html
<!--myModal-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">删除确认框</h4>
        </div>
        <div class="modal-body">
            确定要删除吗？删除之后不可以恢复。
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">提交</button>
        </div>
    </div>
  </div>
</div>

templates/jizhang/foot_botton.html
<div class="btn-group btn-group-justified" role="group">
    <a href="{%url 'jizhang:items'%}" class="btn btn-primary"><span class="glyphicon glyphicon-list-alt"></span> 账单</a>
    <a href="{%url 'jizhang:categories'%}" class="btn btn-primary"><span class="glyphicon glyphicon-th-list"></span> 分类</a>
    <a href="" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> 查找</a>
    <a href="" class="btn btn-primary"><span class="glyphicon glyphicon-modal-window"></span> 报告</a>
</div>

templates/jizhang/items.html
{%extends 'base.html'%}
{%load staticfiles%}
{%block title%}
<title>开始记账吧</title>
{%endblock%}
{%block content%}
<div class="btn-group btn-group-justified" role="group">
    <a href="{%url 'jizhang:new_item'%}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> 新建</a>
    <a href="" class="btn btn-primary"><span class="glyphicon glyphicon-download"></span> 导出</a>
    <a href="" class="btn btn-primary"><span class="glyphicon glyphicon-upload"></span> 导入</a>
    <a href="" class="btn btn-danger" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-trash"></span> 删除</a>
</div>
<form action="" method="post">
    {% csrf_token%}
    <div class="table-response">
        <table class="table table-hover">
                <tr class="info">
                    <td><strong>金额</strong></td>
                    <td><strong>日期</strong></td>
                    <td><strong>分类</strong></td>
                    <td><strong>备注</strong></td>
                    <td><strong><input type="checkbox" name="check_all" value="True" id="all" >全选</strong></td>
                </tr>
            {% if items %}
            {%for i in items%}
                <tr class="{% cycle '' 'active' %}">
                    <td data-toggle="tooltip" data-placement="right" title="编辑该内容"><a href="{{i.get_item_url}}">{{i.price}}</a></td>
                    <td>{{i.pub_date}}</td>
                    <td>{{i.category}}</td>
                    <td>{{i.comment}}</td>
                    <td><input type="checkbox" value="{{i.id}}" class="del_id" name="checkbox"></td>
                </tr>
            {% endfor %}
            {%else %}
                <tr><td><strong>没有账单，开始记账吧</strong></td></tr>
            {%endif%}
        </table>
    <nav>
        <ul class="pager">
                    <li>
                    {% if items.has_previous %}
                    <a href="?page={{items.previous_page_number}}" aria-label="上一页">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                    {% endif %}
                    </li>
                    <li><a href="">{{items.number}}</a></li>
                    <li>
                    {% if items.has_next %}
                    <a href="?page={{items.next_page_number}}" aria-label="下一页">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                    {% endif %}
                    </li>
        </ul>
    </nav>
    </div>
{% include 'jizhang/delete-modal.html'%}
</form>
{% include 'jizhang/foot_botton.html' %}
{%endblock%}

{%block extra_script%}
<script>
    $(function () {
        $("#all").click(function () {
            var checked_status = this.checked;
            $(".del_id").each(function () {
                this.checked = checked_status;
            });
        });
    });
</script>
{% endblock%}

templates/jizhang/new_category.html
{%extends 'base.html'%}
{%load staticfiles%}
{%block title%}
<title>new category</title>
{%endblock%}
{%block content%}
<form action="" method="post">
    {% csrf_token %}
      <div class="form-group">
          <label for="id_username" >分类名</label>
             {{form.name.errors}}
             {{form.name}}
      </div>
      <div class="form-group">
              <label for="id_p_category" >上级分类</label> 
              {{form.p_category.errors}}
              {{form.p_category}}         
      </div>
      <div class="checkbox">
          <label>
             {{form.isincome.errors}}
             {{form.isincome}}是否是收入
          </label>
      </div>
      <input class="btn btn-default" type="submit" value="提交" >
      <a class="btn btn-default" href="{% url 'jizhang:items' %}" role="button">返回</a>
</form>
{%endblock%}

templates/jizhang/new_item.html
{%extends 'base.html'%}
{%load staticfiles%}
{%block title%}
<title></title>
{%endblock%}
{%block content%}
<form action="" method="post">
    {% csrf_token%}
    <div class="form-group">
        <label for="id_price">金额</label>
        {{form.price.errors}}
        {{form.price}}
    </div>
    <div class="form-group">
        <label for="id_category">分类</label>
        {{form.category.errors}}
        {{form.category}}
    </div>
    <div class="form-group" >
        <label for="id_pub_data">日期</label>
        {{form.pub_date.errors}}
        {{form.pub_date}}
    <div class="form-group">
        <label for="id_comment">备注</label>
        {{form.comment.errors}}
        {{form.comment}}
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-default" value="提交">
        <a href="{% url 'jizhang:items' %}" class="btn btn-default" role="button">返回</a>
    </div>
    
</form>
{%endblock%}
{% block extra_script %}
<script>
    $('.datepicker').datetimepicker({
            weekStart: 1,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2,
            forceParse: 0,
            format:'yyyy-mm-dd'
        });
</script>
{% endblock%}